services:
  ets-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/bin
      - /app/obj
    environment:
      - DOTNET_ENVIRONMENT=Development

